### ISSUE TITLE
close automatically old PRs ?

### ISSUE THREAD

**Issue by vincent-fuchs** [societe-generale/ci-droid-tasks-consumer#44]
## Summary

It would be nice to close automatically old PRs. 

https://github.com/societe-generale/ci-droid-tasks-consumer/blob/master/ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/actionHandlers/RebaseHandler.java 

perfoms rebase automatically, so a PR event will be generated.

When that PR event is generated, we could listen to it and close the PR if it's too old

## Type of Issue

It is a : 
 - [x] request

## Motivation

When developers don't close PRs , rebasing several old open PRs can be expensive

implementing a https://github.com/societe-generale/ci-droid-tasks-consumer/blob/master/ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/actionHandlers/PullRequestEventHandler.java would be fairly simple

**Comment by juliette-derancourt** [comment]
I'll try to do that :)

**Comment by vincent-fuchs** [comment]
@juliette-derancourt actually, it may be easier to implement it as a PushEventOnDefaultBranchHandler .

See in https://github.com/societe-generale/ci-droid-tasks-consumer/blob/master/ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/PushEventOnDefaultBranchService.java#L56 , you'll be provided the list of PRs.

It's very easy to then get the creation date of the PR (you'll need to add the field in https://github.com/societe-generale/ci-droid-tasks-consumer/blob/master/ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/model/github/PullRequest.java as it's currently not mapped), and then close the PR if it's beyond the limit.

let's create a new property, similar to https://github.com/societe-generale/ci-droid-tasks-consumer/blob/master/ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/model/github/PullRequest.java , where we can enable and define the threshold (let's default it to 6months, but people may want to override this value)

**Comment by juliette-derancourt** [comment]
You're right, it makes more sense to use this one!

Wasn't your third link supposed to point toward another class?
I agree on the limit being overidable. I'd put a smaller default limit though, like 3 months? It's already a loooong time for a PR to stay alive...
