### ISSUE TITLE
refactor tests to use mock-server instead of code-story

### ISSUE THREAD

**Issue by vincent-fuchs** [societe-generale/ci-droid-tasks-consumer#48]
## Summary

As mentionned by @juliette-derancourt  in #45 , we need to move out of https://github.com/CodeStory/fluent-http which is not actively supported anymore, and use http://www.mock-server.com/ instead.

Mock-server has already been added, so we just need to migrate the tests using fluent-http to mock-server, and remove the dependency.  

## Type of Issue

It is a : 
 - [x] request
 

## Motivation

consistency and clarity : both libs are equivalent, one has more features and is maintained, the other isn't.

**Comment by juliette-derancourt** [comment]
On it!
