### ISSUE TITLE
Upgrade to Spring Boot 2.2.0.M1

### ISSUE THREAD

**Issue by juliette-derancourt** [societe-generale/ci-droid-tasks-consumer#66]
## Summary

I recently noticed that Spring Boot released their first milestone for the [v2.2.0](https://github.com/spring-projects/spring-boot/releases/tag/v2.2.0.M1).
This new version has updated the JUnit Jupiter dependency from 5.3.2 to 5.4.0.
It could be a good thing to upgrade to this version since we had version conflicts for JUnit Jupiter in #61 and #65 (spring was pulling 5.3.2 which forced us to explicitly add the junit-jupiter-api artifact instead of relying entirely on the junit-jupiter aggregate).
Only question is, should we use the milestone or wait for a more stable release?

## Type of Issue
It is a : 
 - [ ] bug
 - [x] request
 - [ ] question regarding the documentation

**Comment by vincent-fuchs** [comment]
Hi,

You can submit a PR with the upgrade if you want. If the build passes, we'll merge it. There's no CI-droid version planned for now, so I guess we'll have time to upgrade to the 2.2.0.RELEASE before we release the next CI-droid version.

**Comment by vincent-fuchs** [comment]
upgraded to 2.2.0.M4 and released v1.2.0.
